### ISSUE TITLE
超时回复好像有问题

### ISSUE THREAD

**Issue by rhwong** [hsyhhssyy/amiyabot-game-hsyhhssyy-duel#1]
2022-12-01 02:27:47,719 [     Bot][   ERROR] handler error: Traceback (most recent call last):
  File "/root/miniconda3/envs/Amiya-Bot/lib/python3.8/site-packages/amiyabot/log/manager.py", line 100, in catch
    yield
  File "/root/miniconda3/envs/Amiya-Bot/lib/python3.8/site-packages/amiyabot/__init__.py", line 59, in __message_handler
    await message_handler(self, event, message)
  File "/root/miniconda3/envs/Amiya-Bot/lib/python3.8/site-packages/amiyabot/factory/messageHandler.py", line 63, in message_handler
    reply = await handler.action(data)
  File "/root/miniconda3/envs/Amiya-Bot/lib/python3.8/site-packages/amiyabot/factory/messageHandlerDefine.py", line 132, in action
    return await self.function(data)
  File "/root/Amiya-Bot/plugins/amiyabot-game-hsyhhssyy-duel-1_1/main.py", line 81, in _
    return Chain(choice,at=False).text('对方30秒内未响应同意')

**Comment by hsyhhssyy** [comment]
厄，你这个日志没截全，最重要的错误名没截到，应该就是紧接着下面的几行，我自己试一下吧，看看能不能复现

**Comment by hsyhhssyy** [comment]
ok，我复现这个错误了，我稍后会上传一个新版本，修复这个问题

**Comment by hsyhhssyy** [comment]
已经在1.2修复
