### ISSUE TITLE
BotAccounts未被定义

### ISSUE THREAD

**Issue by FujiiAkane** [hsyhhssyy/amiyabot-game-hsyhhssyy-duel#4]
该插件正常使用一周后突然报错，卸载重装依旧如此。下面是群员开枪后兔兔返回的结果，请大佬看看要如何解决qaq

handler error: Traceback (most recent call last):
  File "amiyabot\log\manager.py", line 100, in catch
  File "amiyabot\__init__.py", line 67, in __message_handler
  File "amiyabot\factory\messageHandler.py", line 59, in message_handler
  File "amiyabot\factory\messageHandlerDefine.py", line 138, in action
  File "C:\Users\Administrator\Desktop\AmiyaBot-v6.0.12-fix-master\plugins\amiyabot-game-hsyhhssyy-duel-1_4\main.py", line 160, in _
    await mute(data,duel_victim,60*3)
  File "C:\Users\Administrator\Desktop\AmiyaBot-v6.0.12-fix-master\plugins\amiyabot-game-hsyhhssyy-duel-1_4\main.py", line 42, in mute
    map: dict = BotAccounts.get(appid=data.instance.appid)
NameError: name 'BotAccounts' is not defined

**Comment by hsyhhssyy** [comment]
唉
这应该是新版本更新后出现的问题，这几天你可以暂时退回到上一个版本（插件商店里可以安装旧版本的插件），我下个版本会修。

**Comment by FujiiAkane** [comment]
> 唉 这应该是新版本更新后出现的问题，这几天你可以暂时退回到上一个版本（插件商店里可以安装旧版本的插件），我下个版本会修。

感谢，用回1.3版本就正常了。我使用的是v6.0.14-dev的兔兔，1.4版本的决斗仍然报错..

**Comment by hsyhhssyy** [comment]
> 

我提交了一个1.5版本，你试一下好了没有。

**Comment by FujiiAkane** [comment]
> > 
> 
> 我提交了一个1.5版本，你试一下好了没有。

还是报错，兔兔返回的是
handler error: Traceback (most recent call last):
  File "amiyabot\log\manager.py", line 100, in catch
  File "amiyabot\__init__.py", line 69, in __message_handler
  File "amiyabot\factory\messageHandler.py", line 66, in message_handler
  File "amiyabot\factory\messageHandlerDefine.py", line 138, in action
  File "C:\Users\Administrator\Desktop\AmiyaBot-v6.0.12-fix-master\plugins\amiyabot-game-hsyhhssyy-duel-1_5\main.py", line 121, in _
    await mute(data,duel_starter,60*10)
  File "C:\Users\Administrator\Desktop\AmiyaBot-v6.0.12-fix-master\plugins\amiyabot-game-hsyhhssyy-duel-1_5\main.py", line 45, in mute
    requests.post(f'http://{host}:{port}/mute', json={'sessionKey':data.instance.session,'target':data.channel_id,'memberId':target_id,'time':int(mute_time)})
NameError: name 'requests' is not defined
我检查过我的Python是装了requests模块的

**Comment by hsyhhssyy** [comment]
我又更新了一个1.6，你再试试
说实在的，我找不到人和我测试这个功能，所以我没测，只能交给用户去测了。

**Comment by FujiiAkane** [comment]
> 我又更新了一个1.6，你再试试 说实在的，我找不到人和我测试这个功能，所以我没测，只能交给用户去测了。

成功了！而且可以禁言了！尽管我是marai部署的，之前的版本从没有禁言成功过hhhh
辛苦了！
